### ISSUE TITLE
`app.mount()` is not working with `@hono/node-server`

### ISSUE THREAD

**Issue by yusukebe** [honojs/node-server#147]
This code does not work well:

```ts
import { serve } from '@hono/node-server'
import { Hono } from 'hono'

const app = new Hono()

app.mount('/mount', () => {
  return new Response('foo')
})

serve(app)
```

The error message:

```
TypeError: Cannot read properties of undefined (reading 'keepalive')
    at get keepalive [as keepalive] (node:internal/deps/undici/undici:5612:29)
    at Object.RequestInit (node:internal/deps/undici/undici:1779:33)
    at new Request (node:internal/deps/undici/undici:5253:34)
    at Request (/Users/yusuke/work/node/my-app-node/node_modules/@hono/node-server/dist/index.js:55:5)
    at Array.handler (/Users/yusuke/work/node/my-app-node/node_modules/hono/dist/cjs/hono-base.js:191:9)
    at Hono.dispatch (/Users/yusuke/work/node/my-app-node/node_modules/hono/dist/cjs/hono-base.js:235:37)
    at fetch (/Users/yusuke/work/node/my-app-node/node_modules/hono/dist/cjs/hono-base.js:82:19)
    at Server.<anonymous> (/Users/yusuke/work/node/my-app-node/node_modules/@hono/node-server/dist/index.js:399:13)
    at Server.emit (node:events:514:28)
    at Server.emit (node:domain:488:12)
```

**Comment by yusukebe** [comment]
Hi @usualoma 

Can you see this issue? I think this is a definite bug and should be fixed.

**Comment by usualoma** [comment]
Hi @yusukebe 

I think the following PR can fix this issue.
https://github.com/honojs/node-server/pull/148

**Comment by ManuelFernando** [comment]
@yusukebe I had same problem because using app.mount() I can't access to any headers. These are protected, is there a way to read the request. For example when I use **req.headers['content-type']** -> this return **undefined**

**Comment by yusukebe** [comment]
Hi @ManuelFernando 

I can't reproduce it. Please provide a minimal project to reproduce it.

**Comment by ManuelFernando** [comment]
> Hi @ManuelFernando
> 
> I can't reproduce it. Please provide a minimal project to reproduce it.

when it's used console.log(req.headers) in the console appears string representation but any of their field can be accessed

```
import { serve } from '@hono/node-server';
import { Hono } from 'hono';

const app = new Hono();

app.mount('/status', (req) => {
  console.log(req.headers.accept); // -> return undefined
  console.log(req.headers['content-type']) // -> return undefined
  console.log(Object.keys(req.headers)) // -> return []
});

app.get('/', (c) => {
  return c.html(
    <html>
      <body>
        <form method="POST" action="/status">
          <button type="submit">submit</button>
        </form>
      </body>
    </html>
  )
})

const port = 3002;
console.log(`Server is running on port ${port}`);

serve({
  fetch: app.fetch,
  port,
  overrideGlobalObjects: false
});
```

**Comment by yusukebe** [comment]
@ManuelFernando 

The `req.headers` is a [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).

Try:

```ts
req.headers.get('Accept')
```
