### ISSUE TITLE
failed to run that integrated with `webpack-dev-server`

### ISSUE THREAD

**Issue by Hajime-san** [honojs/node-server#209]
The `webpack-dev-server` example failed to run that integrated with latest `@hono/node-server`.

- https://github.com/webpack/webpack-dev-server/tree/543d80f752d2e4cbfa25a88802b196adc2991711/examples/app/hono

```bash
% npx webpack-cli serve
[webpack-cli] Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (node:net:2008:11)
    at READ_WRITE (/path/to/repo/cjs/node_modules/webpack-dev-server/lib/Server.js:3332:23)
    at new Promise (<anonymous>)
    at Server.start (/path/to/repo/cjs/node_modules/webpack-dev-server/lib/Server.js:3330:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/path/to/repo/cjs/node_modules/@webpack-cli/serve/lib/index.js:158:21)
    at async Command.parseAsync (/path/to/repo/cjs/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (/path/to/repo/cjs/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
    at async Command.parseAsync (/path/to/repo/cjs/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async WebpackCLI.run (/path/to/repo/cjs/node_modules/webpack-cli/lib/webpack-cli.js:1360:9) {
  code: 'ERR_SERVER_ALREADY_LISTEN'
}
```

I'm not sure which library should be responsible for listening to the server, but at least in certain versions there is no problem on the `webpack-dev-server` side, so I reported it here.

# Enivironment

```bash
% node --version          
v22.4.0
```

# Steps to reproduce

## Files

- package.json

```json
{
  "type": "module",
  "devDependencies": {
    "@hono/node-server": "^1.13.3",
    "hono": "^4.6.8",
    "webpack": "^5.95.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-middleware": "^7.4.2",
    "webpack-dev-server": "^5.1.0"
  }
}
```

- webpack.config.js

```js
import wdm from "webpack-dev-middleware";
import { Hono } from "hono";
import { serve } from "@hono/node-server";

const app = new Hono();
app.get("/", (c) => {
  return c.text("Hello, Hono!");
})

export default {
  entry: "./app.js",
  devServer: {
    setupMiddlewares: (_, devServer) => [
      {
        name: "webpack-dev-middleware",
        middleware: wdm.honoWrapper(devServer.compiler),
      },
    ],
    app: () => app,
    server: (_, app) =>
      serve({
        fetch: app.fetch,
      }),
  },
};
```

- app.js

```bash
export function add(a, b) {
  return a + b;
}
```

## Command

```bash
% npm ci
% npx webpack-cli serve
```

# My guess

It seems to break after the below PR landed.

- https://github.com/honojs/node-server/pull/206

**Comment by alexander-akait** [comment]
@Hajime-san Yeah, after debugging the problem I found the reason, we have (simplified for the problem):
```
const server = require("@hono/node-server").serve({
  fetch: app.fetch,
});

const listenOptions = this.options.ipc
  ? { path: this.options.ipc }
  : { host: this.options.host, port: this.options.port };

/** @type {S} */
(this.server).listen(listenOptions, () => {
  resolve();
});
``` 

and `listen` doesn't respect `listenOptions`, i.e. `host` and `port` (and based on current implementations that's expected :confused: ), I would say that this is a design api, before `serve` just return `Server` and doesn't run it, but now using `serve` it creates `Server` and run it

**Comment by Hajime-san** [comment]
@alexander-akait 
Thank you for looking into the matter.

NOTE: This issue was fixed below.

- https://github.com/webpack/webpack-dev-server/pull/5347
