### ISSUE TITLE
Response is not defined in `@hono/node-server/vercel`

### ISSUE THREAD

**Issue by alexiglesias93** [honojs/node-server#50]
This is my setup:
```typescript
import { Hono } from 'hono';
import { handle } from '@hono/node-server/vercel';

const app = new Hono().basePath('/api');

app.get('/', (c) => c.json({ message: 'Hello Hono!' }));

// @ts-expect-error
export default handle(app);
```

After silencing the #49 error using `@ts-expect-error`, I get a new error when visiting `http://localhost:3000/api`:
```
file:///C:/Development/honojs-testing/node_modules/.pnpm/@vercel+node@2.14.2/node_modules/@vercel/node/dist/serverless-functions/serverless-handler.mjs:14
        return userCode(req, res);
               ^
ReferenceError: Response is not defined
    at C:\Development\honojs-testing\node_modules\.pnpm\@hono+node-server@1.0.0\node_modules\@hono\node-server\dist\listener.js:30:13
    at Server.<anonymous> (file:///C:/Development/honojs-testing/node_modules/.pnpm/@vercel+node@2.14.2/node_modules/@vercel/node/dist/serverless-functions/serverless-handler.mjs:14:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I can provide a GitHub repository if further context is needed!

**Comment by alexiglesias93** [comment]
My bad, my local NodeJS version was set to `v16.x`, this is why this issue was being caused.
Closing this issue.
