### ISSUE TITLE
`Cannot set property crypto of #<Object> which has only a getter` with Hono 3.2.4 and Node 20.2.0

### ISSUE THREAD

**Issue by MatteoGauthier** [honojs/node-server#57]
```
/Users/matteogauthier/dev/switch/node_modules/.pnpm/@honojs+node-server@0.1.3/node_modules/@honojs/node-server/dist/globals.js:23
    global.crypto = node_crypto_1.default;
           ^


TypeError: Cannot set property crypto of #<Object> which has only a getter
    at installGlobals (/Users/matteogauthier/dev/switch/node_modules/.pnpm/@honojs+node-server@0.1.3/node_modules/@honojs/node-server/dist/globals.js:23:12)
    at <anonymous> (/Users/matteogauthier/dev/switch/node_modules/.pnpm/@honojs+node-server@0.1.3/node_modules/@honojs/node-server/dist/server.js:8:15)
    at Object.<anonymous> (/Users/matteogauthier/dev/switch/node_modules/.pnpm/@honojs+node-server@0.1.3/node_modules/@honojs/node-server/dist/server.js:22:28)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.F (/Users/matteogauthier/dev/switch/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at <anonymous> (/Users/matteogauthier/dev/switch/node_modules/.pnpm/@honojs+node-server@0.1.3/node_modules/@honojs/node-server/dist/index.js:4:16)

Node.js v20.2.0
``` 

my server

```ts
import { serve } from "@honojs/node-server"
import { Hono } from "hono"

const app = new Hono()

app.get("/", (c) => {
  return c.text("Hello world!")
})

serve({
  fetch: app.fetch,
  port: 3111,
})
```

**Comment by yusukebe** [comment]
Hi @MatteoGauthier !

You may use old one!

```
@honojs/node-server
```

To

```
@hono/node-server
```

Try it!

**Comment by marvin-j97** [comment]
> Hi @MatteoGauthier !
> 
> You may use old one!
> 
> ```
> @honojs/node-server
> ```
> 
> To
> 
> ```
> @hono/node-server
> ```
> 
> Try it!

@yusukebe Can confirm this is working fine with `@hono/node-server` in Node 18 and 20. I think you can close this issue.
