### ISSUE TITLE
`500` responses when including `body` payload in any request using `@hono/node-server/vercel`

### ISSUE THREAD

**Issue by alexiglesias93** [honojs/node-server#84]
Whenever we include a payload to a request using `@hono/node-server/vercel`, Hono silently fails and just returns a `500` response.
Here's a minimal repro:
https://github.com/alexiglesias93/hono-vercel-bug/blob/master/api/index.ts

Deployed:
https://hono-vercel-bug.vercel.app/api

I've been able to pinpoint the issue to [these lines](https://github.com/honojs/node-server/blob/main/src/listener.ts#L37-L40) in `listener.ts`, after adding a console log in the `catch` statement I was able to find out that Vercel is failing with this error:
>TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:6342:17)
    at new Request (node:internal/deps/undici/undici:7216:48)
    at file:///C:/Development/hono-vercel-bug/node_modules/.pnpm/@hono+node-server@1.2.0/node_modules/@hono/node-server/dist/listener.mjs:26:33
    at Server.<anonymous> (file:///C:/Development/hono-vercel-bug/node_modules/.pnpm/@vercel+node@2.14.3/node_modules/@vercel/node/dist/serverless-functions/serverless-handler.mjs:14:16)        
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

I also tried to update `vercel` from `29.4.0` to `32.2.5` but still getting a similar error:
>TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:6342:17)
    at new Request (node:internal/deps/undici/undici:7216:48)
    at file:///C:/Development/hono-vercel-bug/node_modules/.pnpm/@hono+node-server@1.2.0/node_modules/@hono/node-server/dist/listener.mjs:26:33
    at Server.<anonymous> (file:///C:/Development/hono-vercel-bug/node_modules/.pnpm/@vercel+node@3.0.5/node_modules/@vercel/node/dist/serverless-functions/serverless-handler.mjs:68:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Any thoughts? This is quite a blocker to implement HonoJS in Vercel ☹️
Let me know if I can do anything to help!

**Comment by alexiglesias93** [comment]
Update: seems [this line](https://github.com/honojs/node-server/blob/main/src/listener.ts#L30) in particular is the one causing the error. If I comment it out, the request goes through without errors.

**Comment by ErickLuis00** [comment]
+1

**Comment by yusukebe** [comment]
Hi!

I started working on fixing this isse, but when I deploy, I get the following error. Are you getting the same error?

<img width="604" alt="Screenshot 2023-09-27 at 18 04 50" src="https://github.com/honojs/node-server/assets/10682/8400a186-0efa-4903-bc25-cd0aaa0694f8">

```txt
Error: Cannot find module '/var/task/node_modules/hono/dist/index.js' imported from /var/task/api/index.js
Did you mean to import hono/dist/cjs/index.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

The project is the same as @alexiglesias93 's .

**Comment by ErickLuis00** [comment]
@yusukebe I had the same error, I'll try to replicate it here because I forgot the reason. I'll get back to you soon. I think it was an issue with the tsconfig file; I'll check.

**Comment by ErickLuis00** [comment]
Remove ```"type": "module"``` from the package.json
and add to tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "strict": true,
    "resolveJsonModule": true
  }
}
```

**Comment by alexiglesias93** [comment]
Seems weird though, I've never had any issues using `"type": "module"` or using the `tsconfig` from Hono's quickstart template 🤔

**Comment by yusukebe** [comment]
@ErickLuis00 Thanks, I'll try it later.

@alexiglesias93 It's weird. When I run it with the edge runtime using the Hono starter, it succeeds, but when I try to run it with Node.js, I get an error.

Anyway, I'll try again.

**Comment by alexiglesias93** [comment]
I'll try to reproduce the issue too

**Comment by yusukebe** [comment]
@alexiglesias93 Only when deploying.

**Comment by yusukebe** [comment]
The main issue, the error occurs when the body doesn't include a payload, is the incoming message stream is closed when it comes to the Node.js Adapter. I think this is specific to the Vercel environment and we are looking for a workaround.

**Comment by alexiglesias93** [comment]
I've been able to reproduce the `FUNCTION_INVOCATION_FAILED`, seems like something in Vercel has changed because I just triggered a redeploy of https://hono-vercel-bug.vercel.app/api and now it's failing.

**Comment by yusukebe** [comment]
Hmm, maybe Vercel changed something in the environment. I'll try again tomorrow.

**Comment by yusukebe** [comment]
Hmmm. I'm still getting errors in the Vercel environment.

As noted here https://github.com/honojs/hono/issues/1256, I think we can get it working with a custom build, but I want to use Verbal CLI, you too right? But maybe not. Hmm.

**Comment by alexiglesias93** [comment]
Yeah,, ideally we'd be able to use Vercel's CLI to get the same experience as when working with edge functions 🤔 
Shall I raise an issue in Vercel's repo? Maybe they can provide some insights.

**Comment by yusukebe** [comment]
@alexiglesias93 

If you are able I would like you to do that!

**Comment by alexiglesias93** [comment]
@yusukebe seems like the errors magically disappeared?
I triggered a new deploy of my repro (https://github.com/alexiglesias93/hono-vercel-bug/blob/master/api/index.ts and
https://hono-vercel-bug.vercel.app/api) and now looks like the deploy works correctly and POST requests work fine when including a payload or headers.

I didn't update any package. Current versions in my repro are:
```json
  "dependencies": {
    "@hono/node-server": "^1.2.0",
    "hono": "^3.6.0"
  },
  "devDependencies": {
    "vercel": "^32.2.5"
  }
```

I've been inspecting and maybe this issue is related to it? https://github.com/vercel/vercel/issues/10564

**Comment by alexiglesias93** [comment]
Yes, I also am getting the error when using `vercel dev`.
Interestingly, I tried adding the `NODEJS_HELPERS=0` environment variable like suggested [here](https://github.com/honojs/hono/issues/1256#issuecomment-1738197919) and now it seems to work fine when using both `vercel dev` and when deploying.
I wonder if this approach has any unwanted side effects? Does Hono rely on [Vercel's NodeJS helpers](https://vercel.com/docs/functions/serverless-functions/runtimes/node-js#node.js-helpers)?

**Comment by alexiglesias93** [comment]
> @alexiglesias93
> 
> Ah, I think so! Since the error is caused by the body being used before it reaches the Hono app handler. Can you able to disable the helper locally?

Yes, we can select what environments a variable must be added to:
![image](https://github.com/honojs/node-server/assets/61051948/86967c7f-f797-4af5-a755-3185a6709504)

I'm curious to know why is it only needed in Development (local) but not in Production (deployed)? Should be add it everywhere just to be safe or is it better to only have it in Development?

**Comment by yusukebe** [comment]
Woooow, it works well! Thanks!

> I'm curious to know why is it only needed in Development (local) but not in Production (deployed)?  Should be add it everywhere just to be safe or is it better to only have it in Development?

I don't know, but I think we should add it everywhere.

**Comment by alexiglesias93** [comment]
Great, then I guess we can close this issue. I'll re-open it if something starts failing again.
Thank you very much for all the insights @yusukebe 🙏🏻

**Comment by ccssmnn** [comment]
I am using Hono in a Next.js API Route. There I got the same behavior: silently failing Hono on POST requests. Configuring the API Route to avoid body parsing helped.

```typescript
export const config = {
  api: {
    bodyParser: false,
  },
};
```

**Comment by arronKler** [comment]
the problem is probably caused by consuming the Request stream twice.

I'm using `vercel dev` to start my project in my local machine.
when I call `ctx.req.json` in a post request, it always report error with `Response body object should not be disturbed or locked`.  I looked the call stack and I found that the `json` call in `honojs/node-server` will execute `new Request()`, and this operation will extracting body (this operation will check the stream is consumed or not).
![image](https://github.com/honojs/node-server/assets/11434728/6ad0df54-01c2-41d0-9830-3344026cd5ca)

And I found another interesting thing is `vercel dev` have an `addHelpers` function which will consume the body stream.
![image](https://github.com/honojs/node-server/assets/11434728/20af8576-0ffe-4ef0-ab98-a71c7ead4a86)

I comment this line and It worked, no error report now.
Accordding to vercel's guide, add NODEJS_HELPER=0 in your project dashboard will solve it. 
[https://vercel.com/docs/functions/serverless-functions/runtimes/node-js#disabling-helpers-for-node.js](https://vercel.com/docs/functions/serverless-functions/runtimes/node-js#disabling-helpers-for-node.js)

So, the final solution for this issue is just add `NODEJS_HELPER=0` in your vercel project.

**Comment by ramiel** [comment]
Should this be mentioned in the docs?

**Comment by cogoo** [comment]
I've investigated the issue with running `vercel dev` for local development and found a solution that might help others facing the same problem.

The issue can be resolved by setting the following environment variable in your local environment file:
```
NODEJS_HELPERS="0"
```

**Comment by prashantchothani** [comment]
@cogoo what is the kind of framework you chose while publishing the app on Vercel ?

**Comment by cogoo** [comment]
We use [Hono][hono.dev], a lightweight app framework.

For deploying on Vercel, we rapp the `app` in a vercel handler:

```js
import { Hono } from 'hono';
import { handle } from '@hono/node-server/vercel';
//.. some other code

const app = new Hono().basePath('/api');
export default handle(app);
```

**Comment by cogoo** [comment]
> @cogoo what is the kind of framework you chose while publishing the app on Vercel ?

We use [Hono](hono.dev]), a lightweight app framework.

For deploying on Vercel, we rapp the `app` in a vercel handler:

```js
import { Hono } from 'hono';
import { handle } from '@hono/node-server/vercel';
//.. some other code

const app = new Hono().basePath('/api');
export default handle(app);
```

**Comment by prashantchothani** [comment]
@cogoo I did the same thing. How do you then have the middleware working with each route having its own function ?

**Comment by prashantchothani** [comment]
Ok will do that. Appreciate your help.

**Comment by prashantchothani** [comment]
@cogoo Please find the stackoverflow link below. I took time to post this because I wanted to test everything that I could to fix it myself but it didn't work:

https://stackoverflow.com/questions/78733581/honojs-with-vercel-middleware-for-backend-api

**Comment by shriharip** [comment]
Hi, I am facing the same issue with firebase functions and wanted to metion it is not just related to vercel. I am using the ```@hono/node-server```  .
my typescript config is 
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "baseUrl": "./",
    "paths": {
			"@/*": ["src/*"]
		}
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

and the code
```
const app = new Hono();

app.use(etag(), honoLogger(), cors());


 app.post('/create-merchant', async (c) => {
		const data = await createMerchant(c);
		return c.json(data)
	})

export const api = onRequest({region: 'europe-west3'}, getRequestListener(app.fetch));
```
My package.json
```
  "engines": {
    "node": "22"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.4.5",
    "@hono/node-server": "^1.13.7",
    "firebase-admin": "^13.0.2",
    "firebase-functions": "^6.3.0",
    "hono": "^4.6.18"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0",
    "typescript": "^5.7.3"
  },
```
